from . import test_main_controller
from . import test_account_payment
from . import test_account_tax_import
from . import test_product_import
from . import test_product
from . import test_res_partner
from . import test_res_partner_category
from . import test_res_partner_import
from . import test_tax
from . import test_xero_error_log
from . import test_xero_integration
from . import test_xero_token
